doc: remove todos
ChainSafe/FIPs pull request #4
Opened 2024-07-12 11:17 UTC by aatifsyed

Now tracked here: https://github.com/ChainSafe/filecoin-common-node-api/issues

2024-07-22 20:06 UTC, ansermino requested changes
For the v0/v1 APIs - I recall we were going to define the path that the API should be served one, whereas these changes seem to only specify which part of the Lotus API we are referencing. Am I remembering that correctly?

2024-07-22 20:06 UTC, ansermino commented on FIPS/fip-common_node_api.md
> +This document aims to specify the _latest_ API version (in this case, `v1`) and breaking changes will be negotiated through further FIPs.
```suggestion
This document aims to specify the `V1` API.
```

"latest" and "version" are a bit confusing here as the version of Lotus is mentioned just before. Additional changes via FIP is defined below.

2024-07-22 20:06 UTC, ansermino commented on FIPS/fip-common_node_api.md
> -
Can't leave a suggestion here, but would suggest an updated list that focuses on what is relevant to readers :
```
- [ ] Improve descriptions for included methods
- [ ] Transfer spec repo to filecoin-project and update links above
- [ ] Add examples to all methods in spec
```

Lmk if you disagree with any of these items.

2024-07-24 02:34 UTC, aatifsyed commented
> For the v0/v1 APIs - I recall we were going to define the path that the API should be served one, whereas these changes seem to only specify which part of the Lotus API we are referencing. Am I remembering that correctly?

Yes, we floated the idea of e.g a `rpc/common-node-api/v1` HTTP path early on.
But we then decided to be "purely descriptive", deferring the following:
- URL paths
- API versioning

I've written this section from that descriptivist PoV - does that match your expectation?

2024-08-07 13:47 UTC, ansermino approved these changes

2024-08-07 13:52 UTC, merged